# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbsnapper < Formula
  desc "Create sanitized development snapshots of your production databases."
  homepage "https://dbsnapper.com/"
  version "0.11.0"
  depends_on :macos

  on_macos do
    url "https://github.com/dbsnapper/dbsnapper/releases/download/v0.11.0/dbsnapper_dbsnapper_0.11.0_Darwin_all.zip"
    sha256 "bbcc914b312fa89690eee62ba33f7639d388806605f851c621b260e98bedec7e"

    def install
      bin.install "dbsnapper"
    end
  end
end
