# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbsnapper < Formula
  desc "Create sanitized development snapshots of your production databases."
  homepage "https://dbsnapper.com/"
  version "1.2.1"
  depends_on :macos

  on_macos do
    url "https://github.com/dbsnapper/dbsnapper/releases/download/v1.2.1/dbsnapper_dbsnapper_1.2.1_Darwin_all.zip"
    sha256 "fe94ee606f051957cd76da3b3c065142d791010fb91eb8eda1d75a0266b65cc7"

    def install
      bin.install "dbsnapper"
    end
  end
end
